// angular-game/src/app/app.component.ts
import { Component } from "@angular/core";
import { shuffle, isEqual } from "lodash";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent {
  colorSequence = shuffle(["green", "red", "yellow", "blue"]);
  userChoices = [];

  checkLossCondition(colorChoice) {
    const correctChoice = this.colorSequence[this.userChoices.length];
    if (correctChoice !== colorChoice) {
      alert("Oh no! You lost! 😭");
      window.location.reload();
    }
  }

  checkWinCondition() {
    const userHasWon = isEqual(this.colorSequence, this.userChoices);
    if (userHasWon) {
      alert("YOU WIN! 🎉");
      window.location.reload();
    }
  }

  handleUserChoice = colorClicked => {
    this.checkLossCondition(colorClicked);
    this.userChoices.push(colorClicked);
    this.checkWinCondition();
  }
}

<div class="app">
  <div class="row-spaced-between">
    <box color="green" [handleUserChoice]="handleUserChoice"></box>
    <box color="red" [handleUserChoice]="handleUserChoice"></box>
  </div>

  <div class="row-centered">
    <flashing-box [colorSequence]="colorSequence"></flashing-box>
  </div>

  <div class="row-spaced-between">
    <box color="yellow" [handleUserChoice]="handleUserChoice"></box>
    <box color="blue" [handleUserChoice]="handleUserChoice"></box>
  </div>
</div>

// react-game/src/App.js
import React from "react";
import { shuffle, isEqual } from "lodash";
import "./App.css";
import Box from "./components/Box";
import FlashingBox from "./components/FlashingBox";

class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      colorSequence: shuffle(["green", "red", "yellow", "blue"]),
      userChoices: []
    };
  }

  handleUserChoice = selectedColor => {
    // first check if the selected color is wrong
    this.checkLossCondition(selectedColor);
    // afterwards, push it into the list of userChoices, with a callback to check the win condition
    this.setState(prevState => {
      return { userChoices: prevState.userChoices.concat(selectedColor) };
    }, this.checkWinCondition);
  };

  checkWinCondition = () => {
    // the user wins if the array of userChoices mirrors the colorSequence
    const { userChoices, colorSequence } = this.state;
    if (isEqual(userChoices, colorSequence)) {
      alert("YOU WIN! 🎉");
      window.location.reload();
    }
  };

  checkLossCondition = nextColorChoice => {
    // the user loses if the correct color choice is not the next selected color
    const correctChoice = this.state.colorSequence[
      this.state.userChoices.length
    ];
    if (correctChoice !== nextColorChoice) {
      alert("Oh no! You lost! 😭");
      window.location.reload();
    }
  };

  render() {
    return (
      <div className="app">
        <div className="row-spaced-between">
          <Box color="green" handleUserChoice={this.handleUserChoice} />
          <Box color="red" handleUserChoice={this.handleUserChoice} />
        </div>

        <div className="row-centered">
          <FlashingBox colorSequence={this.state.colorSequence}></FlashingBox>
        </div>

        <div className="row-spaced-between">
          <Box color="yellow" handleUserChoice={this.handleUserChoice} />
          <Box color="blue" handleUserChoice={this.handleUserChoice} />
        </div>
      </div>
    );
  }
}

export default App;
